--DROP TABLE IHD.DBO.DOCTORS;
-- CREATE DOCTORS TABLE
CREATE TABLE IHD.DBO.DOCTORS(
	ID INT IDENTITY PRIMARY KEY,
	FIRST_NAME VARCHAR(25) NOT NULL,
	LAST_NAME VARCHAR(25),
	EMAIL VARCHAR(25) NOT NULL UNIQUE,
	PRIMARY_CONTACT_NUMBER VARCHAR(20) NOT NULL UNIQUE,
	SECONDARY_CONTACT_NUMBER VARCHAR(20),
	EMERGENCY_CONTACT_NUMBER VARCHAR(20),
	ADDRESS VARCHAR(120),
	ADDRESS_LINE2 VARCHAR(120),
	CITY VARCHAR(30),
	STATE VARCHAR(30),
	COUNTY VARCHAR(30),
	COUNTRY VARCHAR(30),
	CREATED_DATE DATETIME,
	CREATED_BY VARCHAR(30),
	UPDATED_DATE DATETIME,
	UPDATED_BY VARCHAR(30)
);

--INSERT DATA IN DOCTORS TABLE
INSERT INTO [dbo].[DOCTORS]
		   ([FIRST_NAME]
		   ,[LAST_NAME]
		   ,[EMAIL]
		   ,[PRIMARY_CONTACT_NUMBER]
		   ,[SECONDARY_CONTACT_NUMBER]
		   ,[EMERGENCY_CONTACT_NUMBER]
		   ,[ADDRESS]
		   ,[ADDRESS_LINE2]
		   ,[CITY]
		   ,[COUNTY]
		   ,[STATE]
		   ,[COUNTRY]
		   ,[CREATED_DATE]
		   ,[CREATED_BY]
		   ,[UPDATED_DATE]
		   ,[UPDATED_BY])
	 VALUES
		   ('DEV'
		   ,'CHAUHAN'
		   ,'devendra103@gmail.com'
		   ,'2013567349'
		   ,''
		   ,''
		   ,'Sanford Pl'
		   ,'Apt - 2'
		   ,'Jersey City'
		   ,'Hudson'
		   ,'New Jersey'
		   ,'US'
		   ,SYSDATETIME()
		   ,'dchauhan@gmail.com'
		   ,SYSDATETIME()
		   ,'dchauhan@gmail.com');

SELECT * FROM IHD.DBO.DOCTORS;



--DROP TABLE IHD.DBO.PATIENTS;
--CREATE PATIENTS TABLE
CREATE TABLE IHD.DBO.PATIENTS(
	ID INT IDENTITY PRIMARY KEY,
	FIRST_NAME VARCHAR(25) NOT NULL,
	LAST_NAME VARCHAR(25),
	EMAIL VARCHAR(25) NOT NULL UNIQUE,
	PRIMARY_CONTACT_NUMBER VARCHAR(20) NOT NULL UNIQUE,
	SECONDARY_CONTACT_NUMBER VARCHAR(20),
	EMERGENCY_CONTACT_FIRST_NAME VARCHAR(20),
	EMERGENCY_CONTACT_LAST_NAME VARCHAR(20),
	EMERGENCY_CONTACT_RELATIONSHIP VARCHAR(20),
	EMERGENCY_CONTACT_NUMBER VARCHAR(20),
	ADDRESS VARCHAR(120),
	ADDRESS_LINE2 VARCHAR(120),
	CITY VARCHAR(30),
	STATE VARCHAR(30),
	COUNTY VARCHAR(30),
	COUNTRY VARCHAR(30),
	CREATED_DATE DATETIME,
	CREATED_BY VARCHAR(30),
	UPDATED_DATE DATETIME,
	UPDATED_BY VARCHAR(30)
);


--INSERT DATA IN PATIENTS
INSERT INTO [dbo].[PATIENTS]
		   ([FIRST_NAME]
		   ,[LAST_NAME]
		   ,[EMAIL]
		   ,[PRIMARY_CONTACT_NUMBER]
		   ,[SECONDARY_CONTACT_NUMBER]
		   ,[EMERGENCY_CONTACT_FIRST_NAME]
		   ,[EMERGENCY_CONTACT_LAST_NAME]
		   ,[EMERGENCY_CONTACT_RELATIONSHIP]
		   ,[EMERGENCY_CONTACT_NUMBER]
		   ,[ADDRESS]
		   ,[ADDRESS_LINE2]
		   ,[CITY]
		   ,[COUNTY]
		   ,[STATE]
		   ,[COUNTRY]
		   ,[CREATED_DATE]
		   ,[CREATED_BY]
		   ,[UPDATED_DATE]
		   ,[UPDATED_BY])
	 VALUES
		   ('DEV 2'
		   ,'CHAUHAN'
		   ,'devendra03@gmail.com'
		   ,'2013567344'
		   ,''
		   ,'E_FIRSTNAME'
		   ,'E_LASTNAME'
		   ,'E_RELATIONS'
		   ,'2013567349'
		   ,'Sanford Pl'
		   ,'Apt - 2'
		   ,'Jersey City'
		   ,'Hudson'
		   ,'New Jersey'
		   ,'US'
		   ,SYSDATETIME()
		   ,'dchauhan@gmail.com'
		   ,SYSDATETIME()
		   ,'dchauhan@gmail.com');

SELECT * FROM IHD.DBO.PATIENTS;


--DROP TABLE IHD.DBO.VISITS;
--CREATE VISITIS TABLE
CREATE TABLE IHD.DBO.VISITS(
	ID INT IDENTITY PRIMARY KEY,
	PATIENT_ID INT FOREIGN KEY (PATIENT_ID) REFERENCES DBO.PATIENTS (ID),
	DOCTOR_ID INT FOREIGN KEY (DOCTOR_ID) REFERENCES DBO.DOCTORS (ID),
	APPOINTMENT_DATE_TIME DATETIME NOT NULL,
	APPOINTMENT_CREATED_BY VARCHAR(30),
	CREATED_DATE DATETIME,
	CREATED_BY VARCHAR(30),
	UPDATED_DATE DATETIME,
	UPDATED_BY VARCHAR(30)
);

---INSERT DATA IN VISITS
INSERT INTO [dbo].[VISITS] (
	[PATIENT_ID]
	,[DOCTOR_ID]
	,[APPOINTMENT_DATE_TIME]
	,[APPOINTMENT_CREATED_BY]
	,[CREATED_DATE]
	,[CREATED_BY]
	,[UPDATED_DATE]
	,[UPDATED_BY])

VALUES (
	3
	,1
	,SYSDATETIME()
	,'SELF'
	,SYSDATETIME()
   ,'dchauhan@gmail.com'
   ,SYSDATETIME()
   ,'dchauhan@gmail.com'
);

--SHOW VISIT DATA RELATION WITH RESPECT TO DOCTORS RELATION 
SELECT * FROM IHD.DBO.VISITS;

--SHOW ALL VISITORS HISTORY
SELECT P.FIRST_NAME, P.LAST_NAME, CONCAT(D.FIRST_NAME, ' ' , D.LAST_NAME) AS DOCTOR_NAME ,V.*, P.* 
FROM IHD.DBO.VISITS V
LEFT JOIN IHD.DBO.DOCTORS D ON V.DOCTOR_ID  = D.ID
LEFT JOIN IHD.DBO.PATIENTS P ON V.PATIENT_ID= P.ID;

--UPDATE PATIENTS FIRST NAME
UPDATE IHD.DBO.PATIENTS
SET FIRST_NAME = 'JOE'
WHERE ID = 3;

--DELETE VISITIS RECORD BY ID
DELETE FROM IHD.DBO.VISITS WHERE ID = [ID_INT];
